---
- hosts: master
  gather_facts: False

  tasks:
    - pause:
        prompt: "Username for '{{ repo | urlsplit('scheme') + '://' + repo | urlsplit('netloc') }}'"
      register: username
      when: repo is defined

    - pause:
        prompt: "Password for '{{ repo | urlsplit('scheme') + '://' + username.user_input + '@' + repo | urlsplit('netloc') }}'"
        echo: False
      register: password
      when: repo is defined and username.user_input != ""

    - block:

        - name: Create the apps directory, if it doesn't exist
          file:
            path: /opt/spark/apps
            state: directory

        - name: Checkout the Spark application
          git:
            repo: "{{ repo | urlsplit('scheme') + '://' + username.user_input + ':' + password.user_input | urlencode() + '@' + repo | urlsplit('netloc') + repo | urlsplit('path') }}"
            dest: "/opt/spark/apps/{{ (repo | urlsplit('path') | basename | splitext)[0] }}"

      when: repo is defined and username.user_input != "" and password.user_input != ""

    - name: Build Spark application
      shell: mvn clean install
      args:
        chdir: /vagrant

    - name: Remove the output dir, if it exists
      file:
        path: /vagrant/output
        state: absent

    - name: Submit Spark application
      shell: ./bin/spark-submit --master spark://{{ hostvars['master']['ansible_host'] }}:7077 \
              --conf spark.driver.host={{ hostvars['master']['ansible_host'] }} \
              --class uk.co.savvydatainsights.WordCount \
              /vagrant/target/spark-examples-1.0-SNAPSHOT.jar \
              /vagrant/input/lorem-ipsum.txt /vagrant/output
      args:
        chdir: /opt/spark
